name: wg-vanity
on:
  push:
  workflow_dispatch:

jobs:
  build_container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: aarch64-unknown-linux-musl
        - target: arm-unknown-linux-musleabi
        - target: armv7-unknown-linux-musleabi
        - target: x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/wg-vanity
            mchangrh/wg-vanity
          flavor: |
            latest=true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TARGET=${{ matrix.target }}